[package]
name = "meteocli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.28"
config = "0.13.3"
home = "0.5.5"
open-meteo-rs = "0.0.2"
tokio = "1.32.0"
toml = "0.7.6"
